import Cocoa

/// Criteria for matching a notification
struct NotificationMatchCriteria: Codable {
    var appName: String = ""          // Empty = match any app
    var titleContains: String = ""    // Empty = match any title
    var bodyContains: String = ""     // Empty = match any body

    /// Check if all non-empty criteria match the notification content
    func matches(_ content: NotificationContent) -> Bool {
        // All non-empty criteria must match (AND logic)
        if !appName.isEmpty {
            if !content.appName.localizedCaseInsensitiveContains(appName) {
                return false
            }
        }

        if !titleContains.isEmpty {
            if !content.title.localizedCaseInsensitiveContains(titleContains) {
                return false
            }
        }

        if !bodyContains.isEmpty {
            // Check both subtitle and body
            let fullBody = content.subtitle + " " + content.body
            if !fullBody.localizedCaseInsensitiveContains(bodyContains) {
                return false
            }
        }

        return true
    }

    /// Returns true if all criteria are empty (matches everything)
    var isEmpty: Bool {
        return appName.isEmpty && titleContains.isEmpty && bodyContains.isEmpty
    }

    /// Auto-generate a descriptive name from criteria
    var autoGeneratedName: String {
        var parts: [String] = []

        if !appName.isEmpty {
            parts.append(appName)
        }

        if !titleContains.isEmpty {
            parts.append(titleContains)
        }

        if !bodyContains.isEmpty {
            parts.append(bodyContains)
        }

        if parts.isEmpty {
            return "All Notifications"
        }

        // Format: "App: keyword1 keyword2" or just "keyword1 keyword2"
        if !appName.isEmpty && parts.count > 1 {
            let keywords = parts.dropFirst().joined(separator: " ")
            return "\(appName): \(keywords)"
        }

        return parts.joined(separator: " ")
    }
}

/// A notification rule combining match criteria with a style reference
struct NotificationRule: Codable, Identifiable {
    var id: UUID = UUID()
    var name: String = ""  // Empty = auto-generate from criteria
    var criteria: NotificationMatchCriteria = NotificationMatchCriteria()
    var styleId: UUID? = nil  // nil = no custom notification for this rule
    var enabled: Bool = true  // Whether this rule is active

    /// Check if this rule matches the given notification content
    func matches(_ content: NotificationContent) -> Bool {
        return enabled && criteria.matches(content)
    }

    /// Get display name - either custom name or auto-generated from criteria
    var displayName: String {
        if !name.isEmpty {
            return name
        }
        return criteria.autoGeneratedName
    }

    /// Get the style for this rule, if any
    var style: NotificationStyle? {
        guard let styleId = styleId else { return nil }
        return StylesManager.shared.style(withId: styleId)
    }
}

/// Manages notification rules
class RulesManager {
    static let shared = RulesManager()

    private let rulesKey = "notificationRules"
    private let defaultBehaviorKey = "defaultNotificationBehavior"
    private let defaultStyleIdKey = "defaultStyleId"

    private(set) var rules: [NotificationRule] = []

    /// What to do when no rules match
    enum DefaultBehavior: String, Codable {
        case showCustom = "showCustom"      // Show custom notification with default style
        case noCustom = "noCustom"          // Don't show custom notification
    }

    var defaultBehavior: DefaultBehavior {
        get {
            guard let raw = UserDefaults.standard.string(forKey: defaultBehaviorKey),
                  let behavior = DefaultBehavior(rawValue: raw) else {
                return .noCustom
            }
            return behavior
        }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: defaultBehaviorKey)
        }
    }

    /// Style to use when no rules match (if defaultBehavior is .showCustom)
    var defaultStyleId: UUID? {
        get {
            guard let str = UserDefaults.standard.string(forKey: defaultStyleIdKey) else { return nil }
            return UUID(uuidString: str)
        }
        set {
            if let id = newValue {
                UserDefaults.standard.set(id.uuidString, forKey: defaultStyleIdKey)
            } else {
                UserDefaults.standard.removeObject(forKey: defaultStyleIdKey)
            }
        }
    }

    private init() {
        loadRules()
    }

    /// Find the first matching rule for the given notification content
    func findMatchingRule(for content: NotificationContent) -> NotificationRule? {
        for rule in rules {
            if rule.matches(content) {
                return rule
            }
        }
        return nil
    }

    /// Count how many rules use a given style (excluding a specific rule)
    func countRulesUsing(styleId: UUID, excluding ruleId: UUID? = nil) -> Int {
        return rules.filter { rule in
            rule.styleId == styleId && rule.id != ruleId
        }.count
    }

    /// Determine the style to use for a notification, or nil if no custom notification should be shown
    func styleFor(content: NotificationContent) -> NotificationStyle? {
        if let rule = findMatchingRule(for: content) {
            // Rule matched - use its style (or nil if no style set)
            return rule.style
        }

        // No rule matched - use default behavior
        switch defaultBehavior {
        case .showCustom:
            if let styleId = defaultStyleId {
                return StylesManager.shared.style(withId: styleId)
            }
            // Fall back to first available style
            return StylesManager.shared.styles.first
        case .noCustom:
            return nil
        }
    }

    // MARK: - CRUD Operations

    func addRule(_ rule: NotificationRule) {
        rules.append(rule)
        saveRules()
    }

    func updateRule(_ rule: NotificationRule) {
        if let index = rules.firstIndex(where: { $0.id == rule.id }) {
            rules[index] = rule
            saveRules()
        }
    }

    func deleteRule(at index: Int) {
        guard index >= 0 && index < rules.count else { return }
        rules.remove(at: index)
        saveRules()
    }

    func moveRule(from sourceIndex: Int, to destinationIndex: Int) {
        guard sourceIndex >= 0 && sourceIndex < rules.count,
              destinationIndex >= 0 && destinationIndex < rules.count else { return }
        let rule = rules.remove(at: sourceIndex)
        rules.insert(rule, at: destinationIndex)
        saveRules()
    }

    // MARK: - Persistence

    private func loadRules() {
        guard let data = UserDefaults.standard.data(forKey: rulesKey) else {
            rules = []
            return
        }

        do {
            rules = try JSONDecoder().decode([NotificationRule].self, from: data)
        } catch {
            print("Failed to decode rules: \(error)")
            rules = []
        }
    }

    private func saveRules() {
        do {
            let data = try JSONEncoder().encode(rules)
            UserDefaults.standard.set(data, forKey: rulesKey)
        } catch {
            print("Failed to encode rules: \(error)")
        }
    }
}
